services:
  web:
    build: .
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - PYTHONUNBUFFERED=1
    command: ["/app/scripts/entrypoint.sh"]

volumes:
  static_volume:
  media_volume:
